version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      API_PORT: ${API_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
    volumes:
      - ./api/src:/usr/app/api/src
    ports:
      - "3000:${API_PORT}"
      
  fitness-tracker:
    build:
      context: ./fitness-tracker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock