# This is a basic workflow to help you get started with Actions
name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only in the the master branch
  push:
    branches: [ main ]
    
env:
  API_PORT: 3000
  MONGODB_USER: Fit-tracker
  MONGODB_PASSWORD: Workout
  MONGODB_DB: workoutdata

jobs:

 test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose build 
      
      - name: run docker containers
        run: docker-compose up -d
      
      - name: run npm install
        run: |
          cd api
          npm ci
          
      - name: run tests
        run: |
          cd api
          npm run test-ci
 
 build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker-compose build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push in Docker hub
        run: docker-compose push